const subGenres = {
  All: ["All"],
  African: [
    "All",
    "African heavy metal",
    "African hip hop",
    "Afrobeat",
    "Apala",
    "Benga",
    "Bikutsi",
    "Bongo Flava",
    "Cape Jazz",
    "Chimurenga",
    "Congolese rumba",
    "Coupé-Décalé",
    "Fuji music",
    "Genge",
    "Highlife",
    "Hiplife",
    "Igbo highlife",
    "Igbo rap",
    "Isicathamiya",
    "Jit",
    "Jùjú",
    "Kadongo Kamu",
    "Kapuka",
    "Kizomba",
    "Kuduro",
    "Kwaito",
    "Kwassa kwassa",
    "Kwela",
    "Makossa",
    "Maloya",
    "Marrabenta",
    "Mbalax",
    "Mbaqanga",
    "Mbube",
    "Morna",
    "Ndombolo",
    "Palm-wine",
    "Raï",
    "Sakara",
    "Sega",
    "Seggae",
    "Semba",
    "Shangaan electro",
    "Soukous",
    "Taarab",
    "Zouglou",
  ],
  Asian: ["All", "Fann at-Tanbura", "Fijiri", "Khaliji", "Liwa", "Sawt"],
  "Avant-garde": [
    "All",
    "Electroacoustic",
    "Experimental music",
    "Lo-fi",
    "Musique concrète",
    "Noise",
  ],
  Blues: [
    "All",
    "African blues",
    "Blues rock",
    "Blues shouter",
    "British blues",
    "Canadian blues",
    "Chicago blues",
    "Classic female blues",
    "Contemporary R&B",
    "Country blues",
    "Delta blues",
    "Detroit blues",
    "Electric blues",
    "Gospel blues",
    "Hill country blues",
    "Hokum blues",
    "Jump blues",
    "Kansas City blues",
    "Louisiana blues",
    "Memphis blues",
    "Piedmont blues",
    "Punk blues",
    "Rhythm and blues",
    "Soul blues",
    "St. Louis blues",
    "Swamp blues",
    "Texas blues",
    "West Coast blues",
  ],
  Caribbean: [
    "All",
    "2 Tone",
    "Baithak Gana",
    "Bouyon",
    "Cadence-lypso",
    "Calypso",
    "Chutney",
    "Chutney soca",
    "Compas",
    "Dancehall",
    "Dancehall Music",
    "Dub",
    "Lovers rock",
    "Mambo",
    "Merengue",
    "Méringue",
    "Punta",
    "Punta Rock",
    "Ragga",
    "Ragga jungle",
    "Rasin",
    "Reggae",
    "Reggae fusion",
    "Reggaeton",
    "Rocksteady",
    "Rumba",
    "Ska",
    "Ska punk",
    "Soca",
    "Son cubano",
    "Timba",
    "Twoubadou",
    "Zouk",
    "cha cha cha",
    "mosambique",
    "salsa",
    "songo",
  ],
  Country: [
    "All",
    "Alternative country",
    "Americana",
    "Australian country music",
    "Bakersfield sound",
    "Bluegrass",
    "Blues country",
    "Cajun",
    "Cajun fiddle tunes",
    "Christian country music",
    "Classic country",
    "Close harmony",
    "Country pop",
    "Country rap",
    "Country rock",
    "Cowpunk",
    "Dansband music",
    "Franco-country",
    "Hellbilly music",
    "Hokum",
    "Honky Tonk",
    "Instrumental country",
    "Nashville sound",
    "Neotraditional country",
    "Outlaw country",
    "Progressive bluegrass",
    "Progressive country",
    "Psychobilly/Punkabilly",
    "Reactionary bluegrass",
    "Red Dirt",
    "Rockabilly",
    "Sertanejo",
    "Texas country",
    "Traditional country music",
    "Truck-driving country",
    "Western swing",
    "Zydeco",
  ],
  "Easy listening": [
    "All",
    "Background music",
    "Beautiful music",
    "Elevator music",
    "Furniture music",
    "Lounge music",
    "Middle of the road",
    "New-age music",
  ],
  Electronic: [
    "All",
    "2-step garage",
    "4-beat",
    "Acid breaks",
    "Acid house",
    "Acid jazz",
    "Acid techno",
    "Acid trance",
    "Acousmatic music",
    "Afro / Cosmic disco",
    "Aggrotech",
    "Alternative dance",
    "Ambient",
    "Ambient dub",
    "Ambient house",
    "Asian Underground",
    "Balearic beat",
    "Balearic trance",
    "Baltimore club",
    "Bassline",
    "Berlin School",
    "Big beat",
    "Big room",
    "Bitpop",
    "Boogie",
    "Bouncy house",
    "Bouncy techno",
    "Breakbeat",
    "Breakbeat hardcore",
    "Breakcore",
    "Breakstep",
    "Broken beat",
    "Brostep",
    "Bubblegum dance",
    "Chicago house",
    "Chill-out",
    "Chillstep",
    "Chillwave",
    "Chiptune",
    "Coldwave",
    "Complextro",
    "Cybergrind",
    "Dance-pop",
    "Dance-punk",
    "Dance-rock",
    "Dark ambient",
    "Dark electro",
    "Dark wave",
    "Darkcore",
    "Darkcore jungle",
    "Darkstep",
    "Death industrial",
    "Deep house",
    "Detroit techno",
    "Digital hardcore",
    "Disco",
    "Disco polo",
    "Diva house",
    "Doomcore",
    "Downtempo",
    "Dream trance",
    "Drill and bass",
    "Drone music",
    "Drum and bass",
    "Drumstep",
    "Dub",
    "Dub techno",
    "Dubstep",
    "Dubstyle",
    "Dubtronica",
    "Dutch house",
    "Electro house",
    "Electro music",
    "Electro swing",
    "Electro-industrial",
    "Electroacoustic music",
    "Electroclash",
    "Electronic body music",
    "Electronic rock",
    "Electronica",
    "Electronicore",
    "Electropop",
    "Electropunk",
    "Ethereal wave",
    "Ethnic electronica",
    "Euro disco",
    "Eurobeat",
    "Eurodance",
    "Fidget house",
    "Florida breaks",
    "Folktronica",
    "Free tekno",
    "Freestyle music",
    "French house",
    "Full on",
    "Funkstep",
    "Funktronica",
    "Funky house",
    "Future garage",
    "Future house",
    "Futurepop",
    "Gabba",
    "Game Boy music",
    "Garage house",
    "Ghetto house",
    "Glitch",
    "Glitch Hop",
    "Goa trance",
    "Grime",
    "Grindie",
    "Happy hardcore",
    "Hard NRG",
    "Hard house",
    "Hard trance",
    "Hardbag",
    "Hardcore",
    "Hardstep",
    "Hardstyle",
    "Hi-NRG",
    "Hip house",
    "House music",
    "IDM",
    "Illbient",
    "Indietronica",
    "Industrial metal",
    "Industrial music",
    "Industrial rock",
    "Isolationism",
    "Italo dance",
    "Italo disco",
    "Italo house",
    "Japanoise",
    "Jazz house",
    "Jersey club",
    "Jump-up",
    "Jumpstyle",
    "Jungle",
    "Krautrock",
    "Kwaito",
    "Laptronica",
    "Latin house",
    "Lento violento",
    "Liquid dubstep",
    "Liquid funk",
    "Livetronica",
    "Lowercase",
    "Melbourne bounce",
    "Miami bass",
    "Microhouse",
    "Minimal techno",
    "Minimal wave",
    "Moombahcore",
    "Moombahton",
    "Musique concrète",
    "Mákina",
    "Neue Deutsche Härte",
    "Neurofunk",
    "Neurohop",
    "New beat",
    "New rave",
    "New-age music",
    "Nintendocore",
    "Nitzhonot",
    "Nortec",
    "Nu skool breaks",
    "Nu-NRG",
    "Nu-disco",
    "Nu-funk",
    "Nu-gaze",
    "Outsider house",
    "Post-disco",
    "Power electronics",
    "Power noise",
    "Progressive house",
    "Progressive trance",
    "Psybient",
    "Psychedelic trance",
    "Raggacore",
    "Rara tech",
    "Reggaestep",
    "Sambass",
    "Skweee",
    "Space disco",
    "Space music",
    "Space rock",
    "Speed garage",
    "Speedcore",
    "Suomisaundi",
    "Synthpop",
    "Synthwave",
    "Tech house",
    "Tech trance",
    "Techdombe",
    "Techno",
    "Techstep",
    "Tecno brega",
    "Trance music",
    "Trapstep",
    "Tribal house",
    "Trip hop",
    "Trival",
    "Tropical house",
    "UK funky",
    "UK garage",
    "UK hardcore",
    "Uplifting trance",
    "Vaporwave",
    "Video game music",
    "Vocal trance",
    "Witch house",
    "Wonky",
  ],
  Folk: [
    "All",
    "American folk revival",
    "Anti-folk",
    "British folk revival",
    "Celtic music",
    "Chalga",
    "Contemporary folk",
    "Cowboy/Western music",
    "Filk music",
    "Folktronica",
    "Freak folk",
    "Indie folk",
    "Industrial folk",
    "Neofolk",
    "Progressive folk",
    "Protest song",
    "Psychedelic folk",
    "Singer-songwriter",
    "Skiffle",
    "Sung poetry",
  ],
  "Hip hop": [
    "All",
    "Alternative hip hop",
    "Atlanta hip hop",
    "Australian hip hop",
    "Baltimore club",
    "Bongo Flava",
    "Bounce music",
    "Brick City club",
    "British hip hop",
    "Chap hop",
    "Chicago hip hop",
    "Chicano rap",
    "Chopped and screwed",
    "Christian hip hop",
    "Conscious hip hop",
    "Country-rap",
    "Crunk",
    "Crunkcore",
    "Cumbia rap",
    "Detroit hip hop",
    "Drill",
    "East Coast hip hop",
    "Electro music",
    "Experimental hip hop",
    "Freestyle rap",
    "G-funk",
    "Gangsta rap",
    "Ghetto house",
    "Ghettotech",
    "Golden age hip hop",
    "Grime",
    "Hardcore hip hop",
    "Hip house",
    "Hip pop",
    "Hiplife",
    "Horrorcore",
    "Houston hip hop",
    "Hyphy",
    "Igbo rap",
    "Industrial hip hop",
    "Instrumental hip hop",
    "Jazz rap",
    "Jerkin'",
    "Kwaito",
    "Low Bap",
    "Lyrical hip hop",
    "Mafioso rap",
    "Merenrap",
    "Miami bass",
    "Midwest hip hop",
    "Motswako",
    "Nerdcore",
    "New Jersey hip hop",
    "New jack swing",
    "New school hip hop",
    "Old school hip hop",
    "Political hip hop",
    "Ragga",
    "Rap metal",
    "Rap music",
    "Rap opera",
    "Rap rock",
    "Rapcore",
    "Reggae Español/Spanish Reggae",
    "Reggaeton",
    "Snap music",
    "Songo-salsa",
    "Southern hip hop",
    "St. Louis hip hop",
    "Trap",
    "Trip hop",
    "Turntablism",
    "Twin Cities hip hop",
    "Underground hip hop",
    "Urban Pasifika",
    "West Coast hip hop",
  ],
  Jazz: [
    "All",
    "Acid jazz",
    "Afro-Cuban jazz",
    "Asian American jazz",
    "Avant-garde jazz",
    "Bebop",
    "Boogie-woogie",
    "Bossa nova",
    "British dance band",
    "Cape jazz",
    "Chamber jazz",
    "Continental jazz",
    "Cool jazz",
    "Crossover jazz",
    "Dixieland",
    "Ethno jazz",
    "European free jazz",
    "Free funk",
    "Free improvisation",
    "Free jazz",
    "Gypsy jazz",
    "Hard bop",
    "Jazz blues",
    "Jazz fusion",
    "Jazz rap",
    "Jazz rock",
    "Jazz-funk",
    "Kansas City blues",
    "Kansas City jazz",
    "Latin jazz",
    "Livetronica",
    "M-Base",
    "Mainstream jazz",
    "Modal jazz",
    "Neo-bop jazz",
    "Neo-swing",
    "Novelty ragtime",
    "Nu jazz",
    "Orchestral jazz",
    "Post-bop",
    "Punk jazz",
    "Ragtime",
    "Shibuya-kei",
    "Ska jazz",
    "Smooth jazz",
    "Soul jazz",
    "Straight-ahead jazz",
    "Stride jazz",
    "Swing",
    "Third stream",
    "Trad jazz",
    "Vocal jazz",
    "West Coast jazz",
  ],
  Latin: [
    "All",
    "Afro-Cuban jazz",
    "Axé",
    "Bachata",
    "Banda",
    "Bolero",
    "Bossa Nova",
    "Brazilian",
    "Brazilian rock",
    "Brega",
    "Bullerengue",
    "Chicha",
    "Choro",
    "Criolla",
    "Cumbia",
    "Fado",
    "Flamenco",
    "Forró",
    "Frevo",
    "Funk Carioca",
    "Grupera",
    "Guajira",
    "Huayno",
    "Lambada",
    "Latin Christian",
    "Latin alternative",
    "Latin ballad",
    "Latin jazz",
    "Latin pop",
    "Latin rock",
    "Latin swing",
    "Mambo",
    "Maracatu",
    "Mariachi",
    "Merengue",
    "Mexican son",
    "Música criolla",
    "Música popular brasileira",
    "Música sertaneja",
    "Norteño",
    "Nueva canción",
    "Pagode",
    "Porro",
    "Ranchera",
    "Reggaeton",
    "Regional Mexican",
    "Rock en Español",
    "Rumba",
    "Salsa",
    "Salsa romántica",
    "Samba",
    "Samba rock",
    "Son",
    "Tango",
    "Tecnobrega",
    "Tejano",
    "Timba",
    "Tropical",
    "Tropicalia",
    "Tropipop",
    "Vallenato",
    "Zouk-Lambada",
  ],
  Pop: [
    "All",
    "Adult contemporary",
    "Arab pop",
    "Austropop",
    "Baroque pop",
    "Brill Building",
    "Britpop",
    "Bubblegum pop",
    "C-pop",
    "Canción",
    "Canzone",
    "Chalga",
    "Chanson",
    "Christian pop",
    "Classical crossover",
    "Country pop",
    "Dance-pop",
    "Disco polo",
    "Electropop",
    "Eurobeat",
    "Europop",
    "Fado",
    "Folk pop",
    "French pop",
    "Indie pop",
    "Iranian pop",
    "Italo dance",
    "Italo disco",
    "J-pop",
    "Jangle pop",
    "K-pop",
    "Latin ballad",
    "Latin pop",
    "Laïkó",
    "Louisiana swamp pop",
    "Mandopop",
    "Mexican pop",
    "Nederpop",
    "New Romanticism",
    "Operatic pop",
    "Pop rap",
    "Pop rock",
    "Pop soul",
    "Power pop",
    "Progressive pop",
    "Psychedelic pop",
    "Rebetiko",
    "Russian pop",
    "Schlager",
    "Soft rock",
    "Sophisti-pop",
    "Space age pop",
    "Sunshine pop",
    "Surf pop",
    "Synthpop",
    "Teen pop",
    "Traditional pop music",
    "Turkish pop",
    "Vispop",
    "Wonky pop",
    "Worldbeat",
  ],
  "R&B and soul": [
    "All",
    "Blue-eyed soul",
    "Boogie",
    "Contemporary R&B",
    "Deep funk",
    "Disco",
    "Freestyle music",
    "Funk",
    "Go-go",
    "Hip hop soul",
    "Neo soul",
    "New jack swing",
    "Northern soul",
    "P-Funk",
    "Post-disco",
    "Rhythm and blues",
    "Soul",
    "Southern soul",
  ],
  Rock: [
    "All",
    "Acid rock",
    "Alternative metal",
    "Alternative rock",
    "Anarcho punk",
    "Art punk",
    "Art rock",
    "Avant-garde metal",
    "Beat music",
    "Black metal",
    "Canterbury scene",
    "Celtic metal",
    "Celtic punk",
    "Chinese rock",
    "Christian metal",
    "Christian punk",
    "Christian rock",
    "Cowpunk",
    "Crossover thrash",
    "Crust punk",
    "Crustgrind",
    "D-beat",
    "Dark cabaret",
    "Death 'n' roll",
    "Death metal",
    "Death-doom",
    "Deathcore",
    "Deathrock",
    "Desert rock",
    "Digital hardcore",
    "Djent",
    "Doom metal",
    "Dream Pop",
    "Drone metal",
    "Dunedin Sound",
    "Electronic rock",
    "Electronicore",
    "Emo",
    "Experimental rock",
    "Folk metal",
    "Folk punk",
    "Folk rock",
    "Freakbeat",
    "Funk metal",
    "Garage punk",
    "Garage rock",
    "Glam metal",
    "Glam rock",
    "Goregrind",
    "Gothic metal",
    "Gothic rock",
    "Grindcore",
    "Groove metal",
    "Grunge",
    "Gypsy punk",
    "Hard rock",
    "Hardcore punk",
    "Heavy metal",
    "Horror punk",
    "Indie rock",
    "Industrial metal",
    "Industrial rock",
    "Jazz rock",
    "Krautrock",
    "Latin metal",
    "Math rock",
    "Mathcore",
    "Medieval metal",
    "Melodic death metal",
    "Melodic metalcore",
    "Metalcore",
    "Nagoya kei",
    "Neo-psychedelia",
    "Neoclassical metal",
    "Neue Deutsche Härte",
    "New prog",
    "New wave",
    "No wave",
    "Noise rock",
    "Noisegrind",
    "Nu metal",
    "Pagan metal",
    "Paisley Underground",
    "Pop punk",
    "Pop rock",
    "Post-grunge",
    "Post-hardcore",
    "Post-metal",
    "Post-punk",
    "Post-punk revival",
    "Post-rock",
    "Power metal",
    "Powerviolence",
    "Progressive metal",
    "Progressive rock",
    "Psychedelic rock",
    "Psychobilly",
    "Punk rock",
    "Raga rock",
    "Rap metal",
    "Rap rock",
    "Rapcore",
    "Riot grrrl",
    "Rock and roll",
    "Rock in Opposition",
    "Sadcore",
    "Screamo",
    "Shoegaze",
    "Ska punk",
    "Skate punk",
    "Slowcore",
    "Sludge metal",
    "Soft rock",
    "Southern rock",
    "Space rock",
    "Speed metal",
    "Stoner rock",
    "Street punk",
    "Sufi rock",
    "Surf rock",
    "Symphonic black metal",
    "Symphonic metal",
    "Technical death metal",
    "Thrash metal",
    "Thrashcore",
    "Unblack metal",
    "Viking metal",
    "Visual kei",
    "War metal",
    "World fusion",
    "Worldbeat",
  ],
  "Southeast Asian": [
    "All",
    "Baila",
    "Baul",
    "Bhangra",
    "Dangdut",
    "Filmi",
    "Gamelan",
    "Indian pop",
    "Keroncong",
    "Lavani",
    "Luk Krung",
    "Luk Thung",
    "Manila Sound",
    "Morlam",
    "Original Pilipino Music",
    "Pinoy pop",
    "Pop sunda",
    "Ragini",
    "Thai pop",
    "V-pop",
  ],
};

export default subGenres;
